# Generated by Django 4.2.9 on 2024-01-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='summary',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
